# Generated by Django 4.2 on 2023-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nick', models.CharField(max_length=30, verbose_name='Позывной')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telegram', models.CharField(max_length=50, verbose_name='Telegram')),
                ('total_store', models.IntegerField(verbose_name='Сумма покупок в магазине')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
