# Generated by Django 4.2 on 2023-04-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_персональный_номер_player_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birhday',
            field=models.DateField(null=True),
        ),
    ]
