# Generated by Django 4.2 on 2023-04-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_birhday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='birhday',
            new_name='birthday',
        ),
    ]
