# Generated by Django 4.2 on 2023-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_birthday_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='personal_id',
            field=models.CharField(max_length=10, verbose_name='Персональный номер'),
        ),
    ]
