# Generated by Django 4.2 on 2023-04-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='personal_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Персональный номер'),
        ),
    ]
