# Generated by Django 4.2 on 2023-04-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_player_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='personal_hash',
            field=models.CharField(max_length=500, unique=True, verbose_name='Машиночитаемый ID'),
        ),
    ]
