# Generated by Django 4.2 on 2023-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_personal_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='total_store',
            field=models.IntegerField(null=True, verbose_name='Сумма покупок в магазине'),
        ),
    ]
