# Generated by Django 4.2 on 2023-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_player_total_store_achive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achive',
            options={'ordering': ('valid_time',)},
        ),
        migrations.AlterField(
            model_name='player',
            name='personal_hash',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Машиночитаемый ID'),
        ),
    ]
