# Generated by Django 4.2 on 2023-04-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_delete_registration'),
        ('players', '0012_alter_achive_options_alter_player_personal_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achive',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achives', to='players.player'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('player_hash', models.CharField(max_length=300, verbose_name='QR или NFC')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participants', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='players.player')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
    ]
