# Generated by Django 4.2 on 2023-05-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_achive_owner_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achive',
            new_name='Achieve',
        ),
    ]
