# Generated by Django 4.2 on 2023-05-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_rename_achive_achieve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achieve',
            options={'get_latest_by': ('-valid_time',), 'ordering': ('valid_time',)},
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_store',
        ),
        migrations.AlterField(
            model_name='achieve',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achieves', to='players.player'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('total_price', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchases', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
