# Generated by Django 4.2 on 2023-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_achieve_options_remove_player_total_store_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка в магазине', 'verbose_name_plural': 'Покупка в магазине'},
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='personal_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Персональный номер'),
        ),
    ]
