# Generated by Django 4.2 on 2023-04-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название игры')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('org', models.CharField(max_length=30, verbose_name='Ответственный судья')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participants', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
