# Generated by Django 4.2 on 2023-04-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_participants_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='player_hash',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
