# Generated by Django 4.2 on 2023-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_registration_player_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='player_hash',
            field=models.CharField(max_length=300, verbose_name='QR или NFC'),
        ),
    ]
