# Generated by Django 4.2 on 2023-04-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_registration_player_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('date',), 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
    ]
